<?php

return [
    [
        'id' => 'betaine-hcl-pepsin',
        'name' => 'SACCHAROMYCIN bOULARDI',
        'description' => 'Monoglyceride fish oil',
        'price' => 48.99,
        'old_price' => 57.99,
        'image' => '/assets/product-betaine-hcl-pepsin.png',
        'alt' => 'Saccharomycin boulardi supplement bottle',
        'tag_label' => '15% off',
        'tag_class' => 'tag-discount',
        'muted' => true,
    ],
    [
        'id' => 'glutathione-s-liposomal',
        'name' => 'Micellized',
        'description' => 'Vitamin A',
        'price' => 39.99,
        'image' => '/assets/product-glutathione-s-liposomal.png',
        'alt' => 'Micellized supplement bottle',
        'tag_label' => 'Popular',
        'tag_class' => 'tag-popular',
    ],
    [
        'id' => '5-htp-vitamin-b6',
        'name' => 'Saccharomycin boulardi',
        'description' => 'Monoglyceride fish oil',
        'price' => 25.99,
        'old_price' => 44.99,
        'image' => '/assets/product-5htp-vitamin-b6.png',
        'alt' => 'Saccharomycin boulardi supplement bottle',
        'tag_label' => '50% off',
        'tag_class' => 'tag-discount',
        'featured' => true,
    ],
    [
        'id' => 'micellized-vitamin-a',
        'name' => 'Detox boost',
        'description' => 'Glutathione production',
        'price' => 24.99,
        'image' => '/assets/product-micellized-vitamin-a.png',
        'alt' => 'Detox boost supplement bottle',
        'tag_label' => 'Popular',
        'tag_class' => 'tag-popular',
    ],
    [
        'id' => 'b-complex-benfotiamine',
        'name' => 'SACCHAROMYCIN bOULARDI',
        'description' => 'Monoglyceride fish oil',
        'price' => 31.99,
        'image' => '/assets/product-b-complex-benfotiamine.png',
        'alt' => 'Saccharomycin boulardi supplement bottle',
        'muted' => true,
    ],
];
